import React from 'react'
import Head from 'next/head'
import { Container, Space, Title } from '@mantine/core'
import ProductForm from '../components/ProductForm'
import ProductFooter from '../components/ProductFooter'
import { DataProvider } from '../hooks/useData'

export default function Home() {
  return (
    <DataProvider>
      <Head>
        <title>Aston test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ paddingTop: '1rem', paddingBottom: '10rem' }}>
        <Container>
          <Title order={1}>Cestovné poistenie</Title>
          <Space h="md" />

          <ProductForm />
        </Container>
      </main>

      <ProductFooter />
    </DataProvider>
  )
}
